# Generated by Django 4.2.5 on 2023-10-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.IntegerField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
