# Generated by Django 4.2.7 on 2023-12-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_code_course_grades_professor_student_testcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.professor'),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='problem_details',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='MyAppCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.code')),
                ('course', models.ForeignKey(db_column='course_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.course')),
            ],
        ),
    ]
